services:
  db:
    image: postgres:latest
    container_name: twerlo_chat_db
    environment:
      POSTGRES_DB: twerlo_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: twerlo_chat_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=twerlo_chat
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
      - HOST=0.0.0.0
      - MAX_UPLOAD_SIZE=10485760
      - UPLOAD_PATH=./uploads
    volumes:
      - ./uploads:/root/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
